name: 'Docker'
description: 'Build a docker image'
outputs:
  time:
    description: 'Build a docker image'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    MONGODB_URI: $MONGODB_URI
    DATABASE: $DATABASE
  entrypoint: 'python'
  args:
    - '-m'
    - 'unittest'
    - 'discover'
    - '-s'
    - '/app'