on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build docker image
    steps:
    - name: Build a docker image
      id: docker
      uses: actions/covid-map@v1.0
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        DATABASE: ${{ secrets.DATABASE }}