on:
  push:
    branches:
      develop

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build docker image
    steps:
    - name: Build a docker image
      id: docker
      uses: fmcclean/covid-map@develop
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        DATABASE: ${{ secrets.DATABASE }}